name: Pydocstyle

on:
  - push
  - pull_request

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: Pydocstyle install
        run: pip install --user pydocstyle
      - name: Python docstring checks
        run: pydocstyle -v .
