name: Ruff

on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check . --per-file-ignores=tests/*:S101

